REJECTED_ON_CRITICAL_DRIFT = True
REQUIRE_VALIDATION_BEFORE_MATRIXHUB = True
FORBIDDEN_MATRIX_CONTROL_FILES = [
    "MATRIX_BLUEPRINT.yaml",
    "MATRIX_STANDARDS.lock",
    "MATRIX_TASKS.md",
    "MATRIX_ALLOWED_CHANGES.md",
    "MATRIX_ACCEPTANCE_CRITERIA.md",
    "MATRIX_VALIDATION.md",
]
DEPENDENCY_CHANGES_REQUIRE_APPROVAL = True
